apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: stg
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: stg
    role: workload
    take-along-label.capi-to-argocd.role: ""
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: stg-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxCluster
    name: stg
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: stg
  namespace: default
spec:
  allowedNodes:
    - stg-ceph01
    - stg-ceph02
    - stg-ceph04
    - stg-ceph04
    - stg-ceph05
  controlPlaneEndpoint:
    host: 10.4.18.181
    port: 6443
  dnsServers:
    - 10.4.1.1
  ipv4Config:
    addresses:
      - 10.4.18.182-10.4.18.200
    gateway: 10.4.18.129
    prefix: 25
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: stg-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    files:
      - content: |
          apiVersion: v1
          kind: Pod
          metadata:
            creationTimestamp: null
            name: kube-vip
            namespace: kube-system
          spec:
            containers:
            - args:
              - manager
              env:
              - name: cp_enable
                value: "true"
              - name: vip_interface
                value: ""
              - name: address
                value: 10.4.18.181
              - name: port
                value: "6443"
              - name: vip_arp
                value: "true"
              - name: vip_leaderelection
                value: "true"
              - name: vip_leaseduration
                value: "15"
              - name: vip_renewdeadline
                value: "10"
              - name: vip_retryperiod
                value: "2"
              image: ghcr.io/kube-vip/kube-vip:v0.5.11
              imagePullPolicy: IfNotPresent
              name: kube-vip
              resources: {}
              securityContext:
                capabilities:
                  add:
                  - NET_ADMIN
                  - NET_RAW
              volumeMounts:
              - mountPath: /etc/kubernetes/admin.conf
                name: kubeconfig
            hostAliases:
            - hostnames:
              - kubernetes
              ip: 127.0.0.1
            hostNetwork: true
            volumes:
            - hostPath:
                path: /etc/kubernetes/admin.conf
                type: FileOrCreate
              name: kubeconfig
          status: {}
        owner: root:root
        path: /etc/kubernetes/manifests/kube-vip.yaml
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: proxmox://'{{ ds.meta_data.instance_id }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: proxmox://'{{ ds.meta_data.instance_id }}'
    users:
      - name: root
        sshAuthorizedKeys:
          - ssh-ed25519 ...
          - ssh-ed25519 ...
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: ProxmoxMachineTemplate
      name: stg-control-plane
  replicas: 1
  version: v1.28.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: stg-control-plane
  namespace: default
spec:
  template:
    spec:
      format: qcow2
      full: true
      sourceNode: stg-ceph01
      templateID: 166
      network:
        default:
          bridge: vmbr129
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: stg-workers
  namespace: default
spec:
  clusterName: stg
  replicas: 1
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        node-role.kubernetes.io/node: ""
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: stg-worker
      clusterName: stg
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        name: stg-worker
      version: v1.28.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: stg-worker
  namespace: default
spec:
  template:
    spec:
      format: qcow2
      full: true
      sourceNode: stg-ceph01
      templateID: 166
      network:
        default:
          bridge: vmbr129
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: stg-xl-workers
  namespace: default
spec:
  clusterName: stg
  replicas: 2
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        node-role.kubernetes.io/node: ""
        size: "xl"
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: stg-worker
      clusterName: stg
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        name: stg-xl-worker
      version: v1.27.8
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: stg-xl-worker
  namespace: default
spec:
  template:
    spec:
      format: qcow2
      full: true
      sourceNode: stg-ceph01
      templateID: 164
      numSockets: 2
      numCores: 4
      memoryMiB: 16384
      network:
        default:
          bridge: vmbr129
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: stg-worker
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            provider-id: proxmox://'{{ ds.meta_data.instance_id }}'
      users:
        - name: root
          sshAuthorizedKeys:
            - ssh-ed25519 ...
            - ssh-ed25519 ...
