apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cilium
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            role: workload
  template:
    metadata:
      name: '{{name}}-cilium'
    spec:
      project: default
      source:
        repoURL: https://helm.cilium.io
        targetRevision: 1.14.1
        chart: cilium
        helm:
          values: |
            internalTrafficPolicy: local
            image:
              repository: "quay.io/cilium/cilium"
              tag: "v1.14.1"
              useDigest: false
            operator:
              image:
                repository: "quay.io/cilium/operator"
                tag: "v1.14.1"
                useDigest: false
      destination:
        name: '{{name}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      ignoreDifferences:
        - group: ""
          kind: ConfigMap
          name: hubble-ca-cert
          jsonPointers:
            - /data/ca.crt
        - group: ""
          kind: Secret
          name: hubble-relay-client-certs
          jsonPointers:
            - /data/ca.crt
            - /data/tls.crt
            - /data/tls.key
        - group: ""
          kind: Secret
          name: hubble-server-certs
          jsonPointers:
            - /data/ca.crt
            - /data/tls.crt
            - /data/tls.key
